---
- name: set download url for version < 5
  set_fact:
    download_url: "{{ logstash_url_old }}"
    when: logstash_major_version|int < 5

- name: set download url for version >= 5
  set_fact:
    download_url: "{{ logstash_url }}"
    when: logstash_major_version|int >= 5

- name: Download and extract Logstash
  unarchive: src={{ download_url }} dest=/opt/ copy=no

- name: Create softlink for Logstash
  file: src=/opt/logstash-{{logstash_version}} dest=/opt/logstash state=link

- name: Create user for Logstash
  user: name={{logstash_user}} system=yes createhome=yes

- name: Create systemd file for Logstash
  template: src=logstash.service.template dest=/etc/systemd/system/logstash.service
