---
- name: move file
  copy: src=hugepages.sh dest=/etc/temp owner=root group=root

- name: install script to disable transparent huge pages
  shell: install -m 755 /etc/temp /etc/init.d/disable-transparent-hugepages

- name: update disable transparent huge images
  shell: update-rc.d disable-transparent-hugepages defaults
