---
- name: Install a package with apt-get
  apt: name={{ item }} state=present
  with_items: "{{ packages }}"
  when: ansible_os_family == "Debian"

- name: Install a package with yum
  yum: name={{ item }} state=present
  with_items: "{{ packages }}"
  when: ansible_os_family == "RedHat"