---
- name: Download oauth proxy
  get_url: url=https://github.com/bitly/oauth2_proxy/releases/download/v2.0/oauth2_proxy-2.0.linux-amd64.go1.4.2.tar.gz dest=/tmp

- name: Unarchive
  shell: tar -zxf /tmp/oauth2_proxy-2.0.linux-amd64.go1.4.2.tar.gz -C /opt

- name: Rename folder
  shell: mv /opt/oauth2_proxy-2.0.linux-amd64.go1.4.2 /opt/oauth2_proxy

- name: Create oauth2-proxy group
  group: name=oauth2-proxy

- name: Create oauth2-proxy user
  user: name=oauth2-proxy shell=/bin/false home=/opt/oauth2_proxy createhome=no system=yes group=oauth2-proxy

- name: Create systemd file for oauth proxy
  copy: src={{ systemd_file }} dest=/etc/systemd/system/oauth2-proxy.service

- name: Add sysconfig for oauth proxy
  copy: src=sysconfig-oauth2-proxy dest=/etc/default/oauth2-proxy