---
- name: set key
  apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10 state=present

- name: add mongo repo
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse' state=present

- name: update packages
  apt:
    update_cache: yes

- name: install package
  apt:
    name: mongodb-org
    allow_unauthenticated: yes

- name: install sysfsutils
  apt: name=sysfsutils state=present

- name: install rsyslog config
  shell: |
      cat > /etc/rsyslog.d/31-mongo-scripts.conf <<EOF
      local1.*    /var/log/mongodb/scripts.log
      EOF

- name: restart rsyslog
  service: name=rsyslog state=restarted

